// backend/committee/pdfReport.js

// Produces PDF verdict report using pdfkit

import PDFDocument from "pdfkit";

export function buildCommitteePDF(jd, committee, res) {
  const doc = new PDFDocument({ margin: 50, size: "A4" });

  doc.pipe(res);

  const b = jd.wizardData?.basic || {};

  const v = committee.finalVerdict || {};

  // Header

  doc

    .fillColor("#8B0000")

    .fontSize(20)

    .text("ADITYA BIRLA CAPITAL", { align: "center" });

  doc

    .fillColor("#333")

    .fontSize(14)

    .text("JAE Committee Verdict Report", { align: "center" });

  doc.moveDown(1);

  // Role summary box

  doc.fillColor("#000").fontSize(12).text("Role Summary", { underline: true });

  doc.moveDown(0.3);

  doc.fontSize(10);

  const summary = [
    ["Designation", b.designation || "-"],

    ["LOB", b.lob || "-"],

    ["Department", b.department || "-"],

    ["Target Band", b.band || "-"],

    ["Reports To", b.reportsTo || "-"],

    ["Committee ID", committee.id?.slice(0, 8) + "..." || "-"],

    ["Date", new Date(committee.createdAt || Date.now()).toLocaleString()],
  ];

  summary.forEach(([k, val]) => {
    doc
      .text(k + ": ", { continued: true })
      .fillColor("#333")
      .text(val)
      .fillColor("#000");
  });

  doc.moveDown(1);

  // Final Verdict

  doc
    .fillColor("#8B0000")
    .fontSize(14)
    .text("Final Verdict", { underline: true });

  doc.moveDown(0.3);

  doc.fillColor("#000").fontSize(11);

  doc
    .text("Recommended Band: ", { continued: true })

    .fillColor("#8B0000")

    .fontSize(14)

    .text(v.recommendedBand || "-");

  doc.fillColor("#000").fontSize(11);

  doc
    .text("Total Hay Points: ", { continued: true })

    .fillColor("#8B0000")

    .text(String(v.totalPoints || "-"));

  doc.fillColor("#000").fontSize(10).moveDown(0.5);

  doc.text(v.summaryVerdict || "No summary provided.", { align: "justify" });

  doc.moveDown(1);

  // Hay Scoring Breakdown

  doc
    .fillColor("#8B0000")
    .fontSize(14)
    .text("Hay Scoring Breakdown", { underline: true });

  doc.moveDown(0.3);

  doc.fillColor("#000").fontSize(11);

  // Know-How

  doc.fontSize(12).fillColor("#0066cc").text("1. Know-How");

  doc.fontSize(10).fillColor("#000");

  doc.text(
    "Practical: " +
      (v.knowHow?.practical || "-") +
      " | Managerial: " +
      (v.knowHow?.managerial || "-") +
      " | Human Relations: " +
      (v.knowHow?.humanRelations || "-"),
  );

  doc.text("Points: " + (v.knowHow?.points || "-"));

  doc
    .fontSize(9)
    .fillColor("#555")
    .text("Reasoning: " + (v.knowHow?.reasoning || "-"));

  doc.moveDown(0.5);

  // Problem Solving

  doc.fontSize(12).fillColor("#0066cc").text("2. Problem Solving");

  doc.fontSize(10).fillColor("#000");

  doc.text(
    "Environment: " +
      (v.problemSolving?.environment || "-") +
      " | Challenge: " +
      (v.problemSolving?.challenge || "-") +
      " | % of Know-How: " +
      (v.problemSolving?.percentage || "-") +
      "%",
  );

  doc.text("Points: " + (v.problemSolving?.points || "-"));

  doc
    .fontSize(9)
    .fillColor("#555")
    .text("Reasoning: " + (v.problemSolving?.reasoning || "-"));

  doc.moveDown(0.5);

  // Accountability

  doc.fontSize(12).fillColor("#0066cc").text("3. Accountability");

  doc.fontSize(10).fillColor("#000");

  doc.text(
    "Freedom to Act: " +
      (v.accountability?.freedomToAct || "-") +
      " | Magnitude: " +
      (v.accountability?.magnitude || "-") +
      " | Impact: " +
      (v.accountability?.impact || "-"),
  );

  doc.text("Points: " + (v.accountability?.points || "-"));

  doc
    .fontSize(9)
    .fillColor("#555")
    .text("Reasoning: " + (v.accountability?.reasoning || "-"));

  doc.moveDown(1);

  // Debate Transcript

  doc.addPage();

  doc
    .fillColor("#8B0000")
    .fontSize(14)
    .text("Committee Debate Transcript", { underline: true });

  doc.moveDown(0.5);

  (committee.transcript || []).forEach((entry) => {
    doc
      .fillColor("#0066cc")
      .fontSize(11)
      .text(
        "[Round " + entry.round + "] " + (entry.agentName || entry.agentKey),
      );

    doc.fillColor("#000").fontSize(10).text(entry.msg, { align: "justify" });

    doc.moveDown(0.5);
  });

  // Footer

  doc.moveDown(1);

  doc

    .fillColor("#888")

    .fontSize(8)

    .text(
      "Generated by JAE JD Creator | Aditya Birla Capital | " +
        new Date().toLocaleString(),

      { align: "center" },
    );

  doc.end();
}
